// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmS_w5Fw7cDPdnvRa--lQI6hGMizseMC8',
    appId: '1:120548181390:web:15ffbb6f3f2d39514b50df',
    messagingSenderId: '120548181390',
    projectId: 'ide-kuliner',
    authDomain: 'ide-kuliner.firebaseapp.com',
    databaseURL: 'https://ide-kuliner.firebaseio.com',
    storageBucket: 'ide-kuliner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVudDK8itdOZMBm2wg8mYfG_PMy4tYhw',
    appId: '1:120548181390:android:f45538b7938f8ecf4b50df',
    messagingSenderId: '120548181390',
    projectId: 'ide-kuliner',
    databaseURL: 'https://ide-kuliner.firebaseio.com',
    storageBucket: 'ide-kuliner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX12SMIb58QC1TKA2ra2V4jGqBBcNML2k',
    appId: '1:120548181390:ios:dd79b50ab3d5207c4b50df',
    messagingSenderId: '120548181390',
    projectId: 'ide-kuliner',
    databaseURL: 'https://ide-kuliner.firebaseio.com',
    storageBucket: 'ide-kuliner.firebasestorage.app',
    androidClientId: '120548181390-quh38u10fhphh6gah9pv07v3964fo90e.apps.googleusercontent.com',
    iosBundleId: 'elsa.idekuliner.thereds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX12SMIb58QC1TKA2ra2V4jGqBBcNML2k',
    appId: '1:120548181390:ios:6b02d6e10798b1454b50df',
    messagingSenderId: '120548181390',
    projectId: 'ide-kuliner',
    databaseURL: 'https://ide-kuliner.firebaseio.com',
    storageBucket: 'ide-kuliner.firebasestorage.app',
    androidClientId: '120548181390-quh38u10fhphh6gah9pv07v3964fo90e.apps.googleusercontent.com',
    iosBundleId: 'elsa.idekuliner.theredsFlutterLoyalty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmS_w5Fw7cDPdnvRa--lQI6hGMizseMC8',
    appId: '1:120548181390:web:34343c5781c9917f4b50df',
    messagingSenderId: '120548181390',
    projectId: 'ide-kuliner',
    authDomain: 'ide-kuliner.firebaseapp.com',
    databaseURL: 'https://ide-kuliner.firebaseio.com',
    storageBucket: 'ide-kuliner.firebasestorage.app',
  );
}
